#!/usr/bin/env node
/**
 * Miyabi Framework - CLI Entry Point
 * コマンドラインインターフェース
 *
 * Usage:
 *   npx miyabi run <issue-number>  - 特定のIssueを処理
 *   npx miyabi status              - 現在の状態を表示
 *   npx miyabi list                - オープンなIssueを一覧
 */

import dotenv from 'dotenv';
import path from 'path';
import { CoordinatorAgent } from './agents/coordinatorAgent.js';
import { GitHubClient } from './github.js';
import { AgentContext } from './types.js';

// .envを読み込む
dotenv.config();

const LOGO = `
🌸 Miyabi Framework
   自律型開発エージェント
`;

async function main() {
  console.log(LOGO);

  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === 'help') {
    showHelp();
    return;
  }

  // 環境変数をチェック
  const githubToken = process.env.GITHUB_TOKEN;
  const anthropicApiKey = process.env.ANTHROPIC_API_KEY;
  const repository = process.env.REPOSITORY;

  if (!githubToken || githubToken === 'ghp_your_github_token_here') {
    console.error('❌ GITHUB_TOKEN が設定されていません');
    console.error('   .env ファイルに有効なGitHub tokenを設定してください');
    process.exit(1);
  }

  if (!anthropicApiKey || anthropicApiKey === 'sk-ant-your_anthropic_key_here') {
    console.error('❌ ANTHROPIC_API_KEY が設定されていません');
    console.error('   .env ファイルに有効なAnthropic API keyを設定してください');
    process.exit(1);
  }

  if (!repository) {
    console.error('❌ REPOSITORY が設定されていません');
    console.error('   .env ファイルにリポジトリ (例: owner/repo) を設定してください');
    process.exit(1);
  }

  const github = new GitHubClient(githubToken, repository);

  switch (command) {
    case 'run':
      await runIssue(args[1], github, anthropicApiKey, repository);
      break;

    case 'list':
      await listIssues(github);
      break;

    case 'status':
      showStatus(repository);
      break;

    default:
      console.error(`❌ 不明なコマンド: ${command}`);
      showHelp();
      process.exit(1);
  }
}

function showHelp() {
  console.log(`
使用方法:
  npx miyabi run <issue-number>  - 特定のIssueを自動処理
  npx miyabi list                - オープンなIssueを一覧表示
  npx miyabi status              - 現在の状態を表示
  npx miyabi help                - このヘルプを表示

例:
  npx miyabi run 3               - Issue #3 を処理
  npx miyabi list                - 全Issueを表示
`);
}

async function runIssue(
  issueArg: string | undefined,
  github: GitHubClient,
  anthropicApiKey: string,
  repository: string
) {
  if (!issueArg) {
    console.error('❌ Issue番号を指定してください');
    console.error('   例: npx miyabi run 3');
    process.exit(1);
  }

  const issueNumber = parseInt(issueArg, 10);
  if (isNaN(issueNumber)) {
    console.error(`❌ 無効なIssue番号: ${issueArg}`);
    process.exit(1);
  }

  console.log(`\n📋 Issue #${issueNumber} を取得中...`);

  try {
    const issue = await github.getIssue(issueNumber);
    console.log(`   タイトル: ${issue.title}`);
    console.log(`   ラベル: ${issue.labels.join(', ') || '(なし)'}`);

    // コンテキストを作成
    const context: AgentContext = {
      issue,
      repository,
      workDir: process.cwd(),
      githubToken: process.env.GITHUB_TOKEN!,
      anthropicApiKey,
    };

    // Coordinatorを実行
    console.log('\n🚀 Miyabi Coordinator を起動...\n');
    const coordinator = new CoordinatorAgent(context);
    const result = await coordinator.execute();

    // 結果を表示
    console.log('\n' + '='.repeat(50));
    if (result.success) {
      console.log('✅ 処理完了!');

      // GitHubにコメントを追加
      await github.addComment(
        issueNumber,
        `🌸 **Miyabi Agent** が処理を完了しました。\n\n${result.message}\n\n---\n_Generated by Miyabi Framework_`
      );
      console.log('📝 GitHubにコメントを追加しました');
    } else {
      console.log('❌ 処理失敗');
      console.log(`   エラー: ${result.error || result.message}`);
    }

  } catch (error) {
    console.error('❌ エラー:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

async function listIssues(github: GitHubClient) {
  console.log('📋 オープンなIssueを取得中...\n');

  try {
    const issues = await github.listOpenIssues();

    if (issues.length === 0) {
      console.log('   オープンなIssueはありません');
      return;
    }

    for (const issue of issues) {
      const labels = issue.labels.length > 0 ? ` [${issue.labels.join(', ')}]` : '';
      console.log(`  #${issue.number} ${issue.title}${labels}`);
    }

    console.log(`\n合計: ${issues.length}件`);
  } catch (error) {
    console.error('❌ エラー:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

function showStatus(repository: string) {
  console.log(`📊 Miyabi Status\n`);
  console.log(`   リポジトリ: ${repository}`);
  console.log(`   作業ディレクトリ: ${process.cwd()}`);
  console.log(`   GitHub Token: ${process.env.GITHUB_TOKEN ? '✓ 設定済み' : '✗ 未設定'}`);
  console.log(`   Anthropic API Key: ${process.env.ANTHROPIC_API_KEY ? '✓ 設定済み' : '✗ 未設定'}`);
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
